### ISSUE TITLE
Error in Initial Build

### ISSUE THREAD

**Issue by charlesstratton4** [ASP-NET-Core-Boilerplate/Templates#155]
FYI... ASP.Net 5 Boiler Plate > Initial Build > Errors in FilterConfig file. Adding these three using statements fixed the issue.

Environment: Windows 10
Visual Studio Professional 2015 Version 14.0.25431.01

> Added to FilterConfig
  using Boilerplate.Web.Mvc.Filters;
    using NWebsec.Mvc.HttpHeaders.Csp;
    using NWebsec.Mvc.HttpHeaders;

**Comment by RehanSaeed** [comment]
Will give this a try on another machine tomorrow and let you know if I can recreate this.

**Comment by RehanSaeed** [comment]
Thanks, fixed in the next release.
