### ISSUE TITLE
Add PWA opt out to RoborsService

### ISSUE THREAD

**Issue by xperiandri** [ASP-NET-Core-Boilerplate/Templates#169]
Add
```
User-agent: bingbot
Disallow: /manifest.json
```
to `robots.txt` generation according to https://channel9.msdn.com/Events/Build/2017/B8075

Also it would be nice to add stuff specific to PWAs if missing according to https://medium.com/web-on-the-edge/manifoldjs-is-becoming-pwa-builder-to-simplify-building-progressive-web-apps-49bff31f9380

**Comment by RehanSaeed** [comment]
I plan to rewrite the MVC 6 template for dotnet new and with WebPack. A PWA is an optional feature that I would like to add. This issue has been added to the MVC 6 project (See projects tab on GitHub).

BTW, this is by far the best video on PWA's out there https://vimeo.com/214575474.

**Comment by xperiandri** [comment]
Cool! WebPack would be nice.
JSPM better bit WebPack nice
