### ISSUE TITLE
Extension does not create a working application in VS 2017 (15.2)

### ISSUE THREAD

**Issue by andre-artus** [ASP-NET-Core-Boilerplate/Templates#170]
I've made several attempt to generate a working web application using the "ASP.NET Core 1.1.1 MVC 6 Boilerplate (VS 2017 Only)" extension in Visual Studio 2017 (version details below), to no avail.

If I create an application with all default settings it does not produce anything that runs. There are files missing (DevelopmentCertificate.pfx). If I use the file from the "dotnet new bapi" generated site it just gives a blank screen for an inordinately long time. If I run "dotnet restore" then the application will run in ISS Express, but cause an SSL_ERROR_RX_RECORD_TOO_LONG error when running "dotnet run"

"An error occurred during a connection to localhost:5000. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG"

What am I missing? I want an app that I can debug from VS2017, but also run using "dotnet run". An app generated from the built in templates works fine in both cases.

I'm starting a new web application and wanted to try this template, but it's not been fun thus far

**Current VS Setup:**
Microsoft Visual Studio Professional 2017 
Version 15.2 (26430.12) Release
VisualStudio.15.Release/15.2.0+26430.12
Microsoft .NET Framework
Version 4.7.02046

**Comment by RehanSaeed** [comment]
I had trouble with getting DevelopmentCertificate.pfx checked into Git as Git tries to stop you from doing so. This might be a bug if that file is missing. I'll try to take a look as soon as I get a chance.

**Comment by RehanSaeed** [comment]
This should be fixed in the next release.
