### ISSUE TITLE
Forgotten set for URL 

### ISSUE THREAD

**Issue by mdehganr** [ASP-NET-Core-Boilerplate/Templates#185]
Dear Sir

I think there is a little bug on definition of URL in your class, like url is forgetten to be writable, please check attachment and fix it if it is bug.

Regards
![image](https://user-images.githubusercontent.com/16499516/35185250-5f243ae4-fe16-11e7-9707-85b47707ae32.png)

**Comment by RehanSaeed** [comment]
Feel free to reopen if you would like to elaborate.
