### ISSUE TITLE
Web.Config ... <HttpErrors> does not work in Azure WebSite/WebApp

### ISSUE THREAD

**Issue by BishoyDemian** [ASP-NET-Core-Boilerplate/Templates#82]
Thanks for this great project .. it saved me a good amount of time setting it all up myself.

I recently started using the template and it works great on my machine and IIS. However, when I deployed a version to an Azure WebApp, I started getting an infinite redirect loop for any bad URL.

I did some debugging, and I found that the httpErrors config section does not work as expected in Azure WebApps and instead the CustomErrors section should be used.

**Comment by RehanSaeed** [comment]
Let me take a look...

**Comment by RehanSaeed** [comment]
It works on a local IIS but not on Azure. There are some indications that the httpErrors section in Web.config does not work on Azure. I've spent the last hour trying different things without much luck so far.

I've raised [this](https://stackoverflow.com/questions/36527026/how-to-stop-azure-iis-appending-error-status-code-query-string) question and put a bounty on [this](https://serverfault.com/questions/586875/iis-httperrors-executeurl-appends-weird-query-string-like-500http-mysite-com) one.

**Comment by BishoyDemian** [comment]
What I ended up doing is removing the httpErrors section completely and
using CustomErrors instead. it works reliably on bothe, IIS and Azure
WebApps

**Comment by RehanSaeed** [comment]
Can you please post the fragment of config you used to get it working?

**Comment by BishoyDemian** [comment]
Hi Rehan, sorry for the late reply. was a bit busy here.

here is the fragment I changed after removing <httpErrors>

    <customErrors mode="On" defaultRedirect="~/error/generic.html">
>       <error statusCode="400" redirect="/error/badrequest/" />
>       <error statusCode="401" redirect="/error/unauthorized/" />
>       <error statusCode="403" redirect="/error/forbidden.html" />
>       <error statusCode="404" redirect="/error/notfound/" />
>       <error statusCode="405" redirect="/error/methodnotallowed/" />
>       <error statusCode="500" redirect="error\serviceunavailable.html" />
>       <error statusCode="503" redirect="error\serviceunavailable.html" />
>       <error statusCode="504" redirect="error\gatewaytimeout.html" />
>     </customErrors>
